-- MySQL Script generated by MySQL Workbench
-- Thu Apr  9 21:54:33 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema College
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema College
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `College` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `College` ;

-- -----------------------------------------------------
-- Table `College`.`campus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `College`.`campus` (
  `idCampus` INT NOT NULL,
  `Name` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `Address` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`idCampus`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `College`.`major`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `College`.`major` (
  `idMajor` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Campus_idCampus` INT NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `Principal` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMajor`),
  INDEX `fk_major_campus1_idx` (`Campus_idCampus` ASC) VISIBLE,
  CONSTRAINT `fk_major_campus1`
    FOREIGN KEY (`Campus_idCampus`)
    REFERENCES `College`.`campus` (`idCampus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `College`.`personalInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `College`.`personalInfo` (
  `identity` BIGINT(18) UNSIGNED NOT NULL,
  `idType` ENUM('identity card', 'passport') NOT NULL,
  `ChineseName` VARCHAR(45) NOT NULL,
  `EnglishName` VARCHAR(45) NULL,
  `Gender` ENUM('M', 'F') NOT NULL,
  `Birthday` DATE NOT NULL,
  `Nationality` VARCHAR(45) NOT NULL,
  `HomeAddress` VARCHAR(45) NULL,
  `ZipCode` INT UNSIGNED NULL,
  `HomeTel` INT UNSIGNED NULL,
  PRIMARY KEY (`identity`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `College`.`teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `College`.`teacher` (
  `idTeacher` INT NOT NULL,
  `Employment` DATE NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `Major_idMajor` INT NOT NULL,
  `Tital` ENUM('Professor', 'Associate Professor') NOT NULL,
  `PersonalInfo_identity` BIGINT(18) UNSIGNED NOT NULL,
  PRIMARY KEY (`idTeacher`),
  INDEX `fk_teacher_major1_idx` (`Major_idMajor` ASC) VISIBLE,
  INDEX `fk_teacher_personalInfo1_idx` (`PersonalInfo_identity` ASC) VISIBLE,
  CONSTRAINT `fk_teacher_major1`
    FOREIGN KEY (`Major_idMajor`)
    REFERENCES `College`.`major` (`idMajor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_teacher_personalInfo1`
    FOREIGN KEY (`PersonalInfo_identity`)
    REFERENCES `College`.`personalInfo` (`identity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `College`.`grade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `College`.`grade` (
  `idGrade` YEAR(4) NOT NULL,
  PRIMARY KEY (`idGrade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `College`.`class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `College`.`class` (
  `idClass` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Establish` DATE NULL,
  `HeadTeacher_idTeacher` INT NOT NULL,
  `Grade_idGrade` YEAR(4) NOT NULL,
  `Major_idMajor` INT NOT NULL,
  PRIMARY KEY (`idClass`),
  INDEX `fk_class_major1_idx` (`Major_idMajor` ASC) VISIBLE,
  INDEX `fk_class_teacher1_idx` (`HeadTeacher_idTeacher` ASC) VISIBLE,
  INDEX `fk_class_grade1_idx` (`Grade_idGrade` ASC) VISIBLE,
  CONSTRAINT `fk_class_major1`
    FOREIGN KEY (`Major_idMajor`)
    REFERENCES `College`.`major` (`idMajor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_class_teacher1`
    FOREIGN KEY (`HeadTeacher_idTeacher`)
    REFERENCES `College`.`teacher` (`idTeacher`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_class_grade1`
    FOREIGN KEY (`Grade_idGrade`)
    REFERENCES `College`.`grade` (`idGrade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `College`.`changeMajor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `College`.`changeMajor` (
  `idChangeMajor` INT NOT NULL,
  `ChangeDate` DATE NOT NULL,
  `OriginalClass_idClass` INT NOT NULL,
  `CurrentClass_idClass` INT NOT NULL,
  `ChangeCYLMembership` ENUM('Y', 'N', 'N/A') NOT NULL,
  PRIMARY KEY (`idChangeMajor`),
  INDEX `fk_ChangeMajor_class1_idx` (`OriginalClass_idClass` ASC) VISIBLE,
  INDEX `fk_ChangeMajor_class2_idx` (`CurrentClass_idClass` ASC) VISIBLE,
  CONSTRAINT `fk_ChangeMajor_class1`
    FOREIGN KEY (`OriginalClass_idClass`)
    REFERENCES `College`.`class` (`idClass`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ChangeMajor_class2`
    FOREIGN KEY (`CurrentClass_idClass`)
    REFERENCES `College`.`class` (`idClass`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `College`.`changeGrade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `College`.`changeGrade` (
  `idChangeGrade` INT NOT NULL,
  `ChangeDate` DATE NOT NULL,
  `OriginalClass_idClass` INT NOT NULL,
  `CurrentClass_idClass` INT NOT NULL,
  `Reason` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idChangeGrade`),
  INDEX `fk_ChangeGrade_class1_idx` (`OriginalClass_idClass` ASC) VISIBLE,
  INDEX `fk_ChangeGrade_class2_idx` (`CurrentClass_idClass` ASC) VISIBLE,
  CONSTRAINT `fk_ChangeGrade_class1`
    FOREIGN KEY (`OriginalClass_idClass`)
    REFERENCES `College`.`class` (`idClass`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ChangeGrade_class2`
    FOREIGN KEY (`CurrentClass_idClass`)
    REFERENCES `College`.`class` (`idClass`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `College`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `College`.`student` (
  `idStudent` INT NOT NULL,
  `Admission` DATE NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `Class_idClass` INT NULL,
  `PersonalInfo_identity` BIGINT(18) UNSIGNED NOT NULL,
  `ChangeMajor_idChangeMajor` INT NULL,
  `ChangeGrade_idChangeGrade` INT NULL,
  PRIMARY KEY (`idStudent`),
  INDEX `fk_student_class1_idx` (`Class_idClass` ASC) VISIBLE,
  INDEX `fk_student_personalInfo1_idx` (`PersonalInfo_identity` ASC) VISIBLE,
  INDEX `fk_student_ChangeMajor1_idx` (`ChangeMajor_idChangeMajor` ASC) VISIBLE,
  INDEX `fk_student_ChangeGrade1_idx` (`ChangeGrade_idChangeGrade` ASC) VISIBLE,
  CONSTRAINT `fk_student_class1`
    FOREIGN KEY (`Class_idClass`)
    REFERENCES `College`.`class` (`idClass`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_personalInfo1`
    FOREIGN KEY (`PersonalInfo_identity`)
    REFERENCES `College`.`personalInfo` (`identity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_ChangeMajor1`
    FOREIGN KEY (`ChangeMajor_idChangeMajor`)
    REFERENCES `College`.`changeMajor` (`idChangeMajor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_ChangeGrade1`
    FOREIGN KEY (`ChangeGrade_idChangeGrade`)
    REFERENCES `College`.`changeGrade` (`idChangeGrade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `College`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `College`.`course` (
  `idcourse` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Major_idMajor` INT NOT NULL,
  `Examine` ENUM('test', 'speech') NOT NULL,
  PRIMARY KEY (`idcourse`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE,
  INDEX `fk_course_major1_idx` (`Major_idMajor` ASC) VISIBLE,
  CONSTRAINT `fk_course_major1`
    FOREIGN KEY (`Major_idMajor`)
    REFERENCES `College`.`major` (`idMajor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `College`.`schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `College`.`schedule` (
  `Course_idcourse` INT NOT NULL,
  `Teacher_idTeacher` INT NOT NULL,
  `StartYear` YEAR(4) NOT NULL,
  `Semester` ENUM('Spring', 'Autumn') NOT NULL,
  `Weekday` ENUM('Mon', 'Feb', 'Wed', 'Thur', 'Fri', 'Sat') NOT NULL,
  `TimeSlot` ENUM('1', '2', '3', '4', '5', '6', '7', '8', '9') NOT NULL,
  INDEX `fk_schedule_course1_idx` (`Course_idcourse` ASC) VISIBLE,
  INDEX `fk_schedule_teacher1_idx` (`Teacher_idTeacher` ASC) VISIBLE,
  PRIMARY KEY (`StartYear`, `Semester`, `Course_idcourse`),
  CONSTRAINT `fk_schedule_course1`
    FOREIGN KEY (`Course_idcourse`)
    REFERENCES `College`.`course` (`idcourse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_schedule_teacher1`
    FOREIGN KEY (`Teacher_idTeacher`)
    REFERENCES `College`.`teacher` (`idTeacher`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `College`.`student_has_schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `College`.`student_has_schedule` (
  `Student_idStudent` INT NOT NULL,
  `Course_idcourse` INT NOT NULL,
  `SelectYear` YEAR(4) NOT NULL,
  `SelectSemester` ENUM('Spring', 'Autumn') NOT NULL,
  `Score` FLOAT(5,1) UNSIGNED NOT NULL,
  PRIMARY KEY (`Student_idStudent`, `Course_idcourse`),
  INDEX `fk_student_has_schedule_schedule1_idx` (`Course_idcourse` ASC, `SelectYear` ASC, `SelectSemester` ASC) VISIBLE,
  INDEX `fk_student_has_schedule_student1_idx` (`Student_idStudent` ASC) VISIBLE,
  CONSTRAINT `fk_student_has_schedule_student1`
    FOREIGN KEY (`Student_idStudent`)
    REFERENCES `College`.`student` (`idStudent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_has_schedule_schedule1`
    FOREIGN KEY (`SelectYear` , `SelectSemester` , `Course_idcourse`)
    REFERENCES `College`.`schedule` (`StartYear` , `Semester` , `Course_idcourse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
